# Generated by Django 3.1 on 2020-08-18 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 12, 47, 33, 981434), verbose_name='Дата публикации'),
        ),
    ]
